### ISSUE TITLE
error when eslint doesn't match any files

### ISSUE THREAD

**Issue by tobeycodes** [a-b-r-o-w-n/eslint-action#2]
When I delete one file from the repo in PR I get this error. The file I deleted was `src/image.png`

```
##[error]No files matching 'src/image.png' were found.
8
##[error]Node run failed with exit code 1
```

my options
```
repo-token: ***
files: src/**/*
extensions: .js,.jsx,.ts,.tsx
ignore: **/node_modules/**
```

**Comment by tobeycodes** [comment]
I think this is related https://github.com/eslint/eslint/issues/10587

**Comment by a-b-r-o-w-n** [comment]
This could be fixed in eslint, but is definitely a bug in this action 😅 

1. It shouldn't even attempt to lint the file in your example (extension filtering not working as expected).
2. It should skip files that were deleted.

Thanks for the report. I will see what I can do to fix it.

**Comment by a-b-r-o-w-n** [comment]
@schrapel After reading through the linked issue, I think you are right. It seems that passing files to eslint takes precedence over the extensions config. I will whip up a PR to ignore deleted files though.

**Comment by tobeycodes** [comment]
I think we probably need to run our own filtering to check whether any of the modified files in a PR match our actions files and extensions. If it doesn't then we don't even attempt to run eslint

**Comment by a-b-r-o-w-n** [comment]
@schrapel I just pushed a new version. Hopefully that helps!
