### ISSUE TITLE
check endpoint requires GitHub App

### ISSUE THREAD

**Issue by yarinsa** [a-b-r-o-w-n/eslint-action#43]
The endpoint of checks requires a GitHub app. Couldn't find the docs about how to do so, my other alternative is to fork this action and app authentication to the code. What am I missing?
![Screenshot 2023-04-18 at 12 38 27](https://user-images.githubusercontent.com/44482362/232737221-e639f7d7-a549-4d22-b050-51b48c767579.png)

**Comment by a-b-r-o-w-n** [comment]
Closed in #49 by switching to workflow commands instead of the check api.
